from pathlib import Path
import os
import json

from dotenv import load_dotenv
from google import genai
from pydantic import BaseModel


# --------------------------------
# 1. Market Recommendation Schema
# --------------------------------

class MarketRecommendation(BaseModel):
    primary_market: str
    recommended_markets: list[str]
    target_buyers: list[str]
    selling_channels: list[str]
    reasoning: str
    market_opportunities: list[str]


# --------------------------------
# 2. Load API Key
# --------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]

load_dotenv(PROJECT_ROOT / ".env")

api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    raise ValueError("GEMINI_API_KEY not found in .env")


# --------------------------------
# 3. Gemini Client
# --------------------------------

client = genai.Client(api_key=api_key)


# --------------------------------
# 4. Product Information
# --------------------------------

# Load catalog generated by Catalog AI
catalog_path = PROJECT_ROOT / "ai" / "data" / "catalog.json"

if not catalog_path.exists():
    raise FileNotFoundError(
        "catalog.json not found. Run catalog.py first."
    )

with open(catalog_path, "r", encoding="utf-8") as f:
    product = json.load(f)


# --------------------------------
# 5. Market Analysis Prompt
# --------------------------------

prompt = f"""
You are the AI Market Recommendation Assistant for CraftConnect.

CraftConnect helps marginalized artisans find suitable markets
and buyers for their handcrafted products.

Analyze the following product information and recommend
the most suitable markets in India and online.

PRODUCT:

Name:
{product["product_name"]}

Category:
{product["category"]}

Craft Type:
{product["craft_type"]}

Material:
{product["material"]}

Description:
{product["description"]}

Tags:
{", ".join(product["tags"])}


IMPORTANT:

1. Identify the strongest primary market for this product.
2. Suggest 4-6 additional realistic markets.
3. Identify specific types of customers who may buy it.
4. Suggest suitable selling channels.
5. Explain why these markets are suitable.
6. Identify practical business opportunities for the artisan.
7. Do not invent specific buyers or companies.
8. Focus on realistic Indian handicraft and home-decor markets.
9. Consider festive, gifting and online opportunities.
"""


# --------------------------------
# 6. Ask Gemini
# --------------------------------

interaction = client.interactions.create(
    model="gemini-3.6-flash",

    input=prompt,

    response_format={
        "type": "text",
        "mime_type": "application/json",
        "schema": MarketRecommendation.model_json_schema()
    }
)


# --------------------------------
# 7. Convert Response
# --------------------------------

market = MarketRecommendation.model_validate_json(
    interaction.output_text
)


# --------------------------------
# 8. Display Result
# --------------------------------

print("\n====================================")
print("   CRAFTCONNECT AI MARKET ANALYSIS")
print("====================================\n")

print(json.dumps(
    market.model_dump(),
    indent=2,
    ensure_ascii=False
))

# -----------------------------
# Save Market Recommendation
# -----------------------------

DATA_DIR = PROJECT_ROOT / "ai" / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

market_path = DATA_DIR / "market.json"

with open(market_path, "w", encoding="utf-8") as f:
    json.dump(
        market.model_dump(),
        f,
        indent=2,
        ensure_ascii=False
    )

print(f"\nMarket recommendation saved to: {market_path}")