from pathlib import Path
import os
import json

from dotenv import load_dotenv
from google import genai
from pydantic import BaseModel


# --------------------------------
# 1. Demand & Trend Schema
# --------------------------------

class DemandTrend(BaseModel):
    demand_score: int
    demand_level: str
    peak_seasons: list[str]
    high_demand_periods: list[str]
    low_demand_periods: list[str]
    demand_drivers: list[str]
    inventory_recommendation: str
    trend_summary: str


# --------------------------------
# 2. Load API Key
# --------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]

load_dotenv(PROJECT_ROOT / ".env")

api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    raise ValueError("GEMINI_API_KEY not found in .env")


# --------------------------------
# 3. Gemini Client
# --------------------------------

client = genai.Client(api_key=api_key)


# --------------------------------
# 4. Product Information
# --------------------------------

# Load catalog generated by Catalog AI
catalog_path = PROJECT_ROOT / "ai" / "data" / "catalog.json"

if not catalog_path.exists():
    raise FileNotFoundError(
        "catalog.json not found. Run catalog.py first."
    )

with open(catalog_path, "r", encoding="utf-8") as f:
    product = json.load(f)


# --------------------------------
# 5. Demand Analysis Prompt
# --------------------------------

prompt = f"""
You are the Demand and Trend Intelligence AI for CraftConnect.

CraftConnect helps marginalized Indian artisans understand
when and where their products are likely to have higher demand.

Analyze the following product:

PRODUCT NAME:
{product["product_name"]}

CATEGORY:
{product["category"]}

CRAFT TYPE:
{product["craft_type"]}

MATERIAL:
{product["material"]}

DESCRIPTION:
{product["description"]}

TAGS:
{", ".join(product["tags"])}


TASK:

Estimate the likely demand pattern for this product in India.

Consider:

1. Product category
2. Decorative and gifting value
3. Festival-related demand
4. Wedding and event demand
5. Seasonal shopping behavior
6. Cultural relevance
7. Likely online and offline demand
8. Inventory planning


IMPORTANT RULES:

- Give a demand score from 0 to 100.
- The score should represent estimated market opportunity,
  NOT guaranteed sales.
- Use "High", "Medium", or "Low" for demand_level.
- Identify important peak seasons.
- Identify periods where demand may be lower.
- Explain the major factors driving demand.
- Give a practical inventory recommendation for an artisan.
- Do not claim access to private sales data.
- Do not invent exact sales numbers.
- Clearly describe the result as an AI-based estimate.
"""


# --------------------------------
# 6. Ask Gemini
# --------------------------------

interaction = client.interactions.create(
    model="gemini-3.6-flash",

    input=prompt,

    response_format={
        "type": "text",
        "mime_type": "application/json",
        "schema": DemandTrend.model_json_schema()
    }
)


# --------------------------------
# 7. Convert Response
# --------------------------------

trend = DemandTrend.model_validate_json(
    interaction.output_text
)


# --------------------------------
# 8. Display Result
# --------------------------------

print("\n====================================")
print("   CRAFTCONNECT DEMAND & TREND AI")
print("====================================\n")

print(json.dumps(
    trend.model_dump(),
    indent=2,
    ensure_ascii=False
))